# Generated by Django 5.0.7 on 2024-07-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('salary_expectation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experience', models.TextField()),
                ('highest_education', models.CharField(max_length=100)),
            ],
        ),
    ]
