# Generated by Django 5.0.7 on 2024-07-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
