# Generated by Django 5.0.7 on 2024-07-27 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_jobposting_education_level_and_more'),
        ('users', '0002_alter_application_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.jobposting'),
            preserve_default=False,
        ),
    ]
