# Generated by Django 5.0.7 on 2024-07-28 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_education_level_application_highest_education_and_more'),
        ('users', '0003_application_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to='companies.jobposting'),
        ),
    ]
