# Generated by Django 5.0.7 on 2024-07-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('salary_range', models.CharField(max_length=50)),
                ('requirements', models.TextField()),
                ('education_level', models.CharField(max_length=50)),
            ],
        ),
    ]
