# Generated by Django 5.0.7 on 2024-07-27 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='education_level',
            field=models.CharField(choices=[('fundamental', 'Ensino fundamental'), ('medio', 'Ensino médio'), ('tecnologo', 'Tecnólogo'), ('superior', 'Ensino Superior'), ('pos_mba_mestrado', 'Pós / MBA / Mestrado'), ('doutorado', 'Doutorado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(choices=[('up_to_1000', 'Até 1.000'), ('1000_to_2000', 'De 1.000 a 2.000'), ('2000_to_3000', 'De 2.000 a 3.000'), ('above_3000', 'Acima de 3.000')], max_length=50),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary_expectations', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experience', models.TextField()),
                ('education_level', models.CharField(max_length=100)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='companies.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
