# Generated by Django 5.0.7 on 2024-07-28 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_jobposting_education_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='education_level',
            new_name='highest_education',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='salary_expectations',
            new_name='salary_expectation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='requirements',
        ),
        migrations.AddField(
            model_name='application',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_applications', to='companies.jobposting'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
